- id: orca-cli-secrets
  name: Orca Security - Secret Detection
  description: Detect hardcoded secrets using orca-cli
  entry: orca-cli --silent --skip-scan-log -p secret-orca-demo fs scan ./ --staged-secrets --security-checks secret
  language: system
  stages: [commit]
  pass_filenames: false

- id: docker-orca-cli-secrets
  name: Orca Security - Secret Detection
  description: Detect hardcoded secrets using orca-cli
  entry: -e ORCA_SECURITY_PROJECT_KEY -e ORCA_SECURITY_API_TOKEN ghcr.io/orcasecurity/orca-cli:latest --silent --staged-secrets --skip-scan-log -p secret-orca-demo fs scan /src --security-checks secret
  language: docker_image
  stages: [commit]
  pass_filenames: false

