- id: orca-shiftleft
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using orca-cli
  entry: orca-cli -p $ORCA_SECURITY_SF_PROJECT_KEY --silent --api-token $ORCA_SECURITY_API_TOKEN fs scan ./ --security-checks secret
  language: system
  stages: [commit]
  pass_filenames: false
